"""PyTorch correctness reference for the decoder-attention block."""

from .decoder_attention import (
    DecoderAttentionConfig,
    DecoderAttentionDebug,
    DecoderAttentionResult,
    apply_rope_reference,
    decoder_attention_reference,
    gqa_attention_reference,
    linear_reference,
    reshape_heads_reference,
    rms_norm_reference,
)
from .nvfp4 import (
    E2M1_MAX,
    NVFP4_BLOCK_SIZE,
    NVFP4_GLOBAL_RANGE,
    NVFP4ErrorMetrics,
    NVFP4Tensor,
    UE4M3_MAX,
    analyze_nvfp4_error,
    compute_nvfp4_global_scales,
    decode_e2m1,
    decode_ue4m3,
    dequantize_nvfp4_reference,
    encode_e2m1,
    encode_ue4m3,
    pack_e2m1_codes,
    quantize_nvfp4_reference,
    unpack_e2m1_codes,
)
from .w4a16 import w4a16_linear_reference

__all__ = [
    "DecoderAttentionConfig",
    "DecoderAttentionDebug",
    "DecoderAttentionResult",
    "E2M1_MAX",
    "NVFP4_BLOCK_SIZE",
    "NVFP4_GLOBAL_RANGE",
    "NVFP4ErrorMetrics",
    "NVFP4Tensor",
    "UE4M3_MAX",
    "analyze_nvfp4_error",
    "apply_rope_reference",
    "compute_nvfp4_global_scales",
    "decode_e2m1",
    "decode_ue4m3",
    "decoder_attention_reference",
    "dequantize_nvfp4_reference",
    "encode_e2m1",
    "encode_ue4m3",
    "gqa_attention_reference",
    "linear_reference",
    "pack_e2m1_codes",
    "quantize_nvfp4_reference",
    "reshape_heads_reference",
    "rms_norm_reference",
    "unpack_e2m1_codes",
    "w4a16_linear_reference",
]
